### ISSUE TITLE
Remove *.csproj *.unityproj *.sln from .gitignore file

### ISSUE THREAD

**Issue by SeppPenner** [hiroyky/HololensQrCodeReader#1]
I don't know if you did it on purpose but a project without project files (*.csproj, *.unityproj, *.sln) is quite useless...

**Comment by tmhab** [comment]
Incorrect, those are autogenerated (at least the base level .csproj and .sln) and should be added to the .gitignore.

**Comment by SeppPenner** [comment]
What? Since when is a *.sln file auto-generated every time? These files are needed to run the projects. Without them, you can just look at the *.cs files in Notepad and do nothing else... They are relevant and should never be in the gitignore file.

**Comment by tmhab** [comment]
You are mistaken. This is how Unity has worked for many years now. The solution and project files are generated by Unity as needed. They should not be checked in.

https://github.com/github/gitignore/blob/master/Unity.gitignore

https://gamedev.stackexchange.com/a/50188

**Comment by SeppPenner** [comment]
@tmhab You're right by now. When I created this issue, the automatic creation didn't work (At least for me).
